### ISSUE TITLE
Bette styling

### ISSUE THREAD

**Issue by bacloud14** [bacloud14/Interactive_Arrays#3]
I believe style is horrible, and I need a helping hand. It does not need to support Mobile phone, as developer console is not supported (advance settings to open it). So I do not intend to support mobile version at all.

**Comment by ErHarshal** [comment]
I can do

**Comment by bacloud14** [comment]
I would be grateful, make a pull request I will accept. For now, you can see that I just put [picnic ](https://picnicss.com/) styling just to have basic styling, but layout is not that good.
Feel free to style it as you like, even colors.
Thanks !

**Comment by bacloud14** [comment]
@ErHarshal  Any follow up from your side ?

**Comment by Shivansh1552** [comment]
I can fix the styling but will not be responsive though

**Comment by bacloud14** [comment]
it is yours ! of course, it is not the purpose anyway, not for light terminals: phones, tablets ...

**Comment by bacloud14** [comment]
Hi ErHarshal !
I am working on a little new project, it would be nice if you put your magnificent touch again !
Check this: 
Live demo: https://bacloud14.github.io/js_arules/
Styling issue: https://github.com/bacloud14/js_arules/issues/1
I would like to include your name again on the bottom with mine.
Many thanks !

**Comment by bacloud14** [comment]
I reopen for even better styling? Giving it a try

**Comment by Shivansh1552** [comment]
Okkay. I will try to style it better than before.

**Comment by bacloud14** [comment]
Oh @Shivansh1552 thanks for your attention and good luck!

**Comment by bacloud14** [comment]
Any follow up? Thanks

**Comment by Shivansh1552** [comment]
There was actually some technical issue in the laptop and so sent it for
repair and hence was not able to do anything since 2 days. I got my laptop
repaired today and will soon start to work on it. Thanks

**Comment by bacloud14** [comment]
Ok bro, no hurry just asking, good luck 🤞

**Comment by mbabkina** [comment]
Hello @bacloud14 !
Do you still need help with styling?
Also did you consider creating the separate css file with styling only?

**Comment by bacloud14** [comment]
Sure, but this is like enhancement, nothing specific, so if you feel like improving by your taste, feel free to propose as a PR. I just like simple designs. 
Thanks

**Comment by dksmith328** [comment]
Hey @bacloud14. Is this project still available?

**Comment by bacloud14** [comment]
Hello @dksmith328 
Glad you are showing interest. Style went through stages with kind contributors.

A better style, is always welcome, so yes still and always open.

Feel free to work on. Many thanks.

**Comment by dksmith328** [comment]
Excellent. I will keep in touch.
